# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

inhibit_all_warnings!

pod 'Haneke', '~> 1.0'
pod 'Cloudinary', '~> 1.0'
pod 'UIImage+Additions'
pod 'UIColor+Additions'
