# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MJiOSCore' do
  use_frameworks!

  # Pods for MJiOSCore

  pod 'Haneke', '~> 1.0'
  pod 'Cloudinary', '~> 1.0'

  target 'MJiOSCoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MJiOSCoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
